8|2024-09-18T12:20:37.1969960+00:00|INFO|2|SystemUiLanguageTracker|System language is ru, but that language is not in the list of supported languages for our app.
19|2024-09-18T12:20:37.3916283+00:00|INFO|2|AnalysisLogService|**DEVICE:{"id":1,"name":"DEMO","connectionState":"Uninitialized","firmware":null}
20|2024-09-18T12:20:37.3926275+00:00|INFO|2|AnalysisLogService|**DEVICE_CONNECT:{"id":1}
23|2024-09-18T12:20:37.4266080+00:00|INFO|2|SystemInformationService|
--------------------------------------------------------------------------------
application name                        Tacx Desktop app
application version                     4.38.1.0
cloud environment                       Live
culture                                 Russian
device family                           Windows.Desktop
operating system                        WINDOWS
OS version                              10.0.17763.6189
architecture                            X64
available memory                        10,103
device model                            SVP1321J1RBI
device manufacturer                     Sony Corporation
--------------------------------------------------------------------------------
24|2024-09-18T12:20:37.4276073+00:00|INFO|2|AnalysisLogService|**GENERAL:{"applicationName":"Tacx Desktop app","applicationVersion":"4.38.1.0","culture":"ru","operatingSystem":"WINDOWS","operatingSystemVersion":"10.0.17763.6189","operatingSystemArchitecture":"X64","availableMemory":10102882304,"deviceFamily":"Windows.Desktop"}
26|2024-09-18T12:20:37.6444825+00:00|INFO|2|AnalysisLogService|**CONNECTION_INTERNET:{"hasAdapter":true,"isConnected":true,"mediumType":"Wireless","networkAdapterId":"c778ba02-0fed-451b-a54f-3db8e594efd5"}
32|2024-09-18T12:20:37.6644712+00:00|INFO|5|FilmsLocationService|FilmsLocationService Initialized
37|2024-09-18T12:20:40.8196584+00:00|ERROR|2|ICloudServiceManager|Method: <GetJwtAsync>b__0 calling with empty token.
36|2024-09-18T12:20:40.8196584+00:00|ERROR|10|ICloudServiceManager|Method: <GetDevicesAsync>b__0 calling with empty token.
51|2024-09-18T12:20:41.2004395+00:00|ERROR|46|DatabaseService|Failed to select Primary_Key, WorkoutID, Quality, DownloadID, FileSize, AccessListToken, VideoVersion from table DownloadingVideos. --> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DownloadingVideos'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3) + 0x9c
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior) + 0x21b
   at Tacx.UWP.Services.DatabaseService.SelectFromTableInternal(String, IList`1, ICollection`1, Boolean) + 0x173

54|2024-09-18T12:20:41.8905211+00:00|INFO|46|FilmDownloadService|FilmDownloadService initialized
56|2024-09-18T12:20:42.2533123+00:00|WARN|11|UwpAntService|Unknown request received initialize_completed
57|2024-09-18T12:20:42.4412033+00:00|ERROR|2|FirebaseTokenGenerator|Error in GetTokenInternalAsync --> Tacx.Cloud.Apis.Common.CloudApiException: Error calling UserGetJWT: { "statusCode": 401, "message": "Not authorized" } ---> Tacx.Cloud.Apis.FromSwagger.Client.ApiException: Error calling UserGetJWT: { "statusCode": 401, "message": "Not authorized" }
   at Tacx.Cloud.Apis.FromSwagger.Api.TacxCloud.UserApi.<UserGetJWTAsyncWithHttpInfo>d__62.MoveNext() + 0x1b85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.Cloud.Apis.FromSwagger.Api.TacxCloud.UserApi.<UserGetJWTAsync>d__61.MoveNext() + 0x97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.Cloud.Services.UserCloudService.<>c__DisplayClass25_0.<<UserGetJwtAsync>b__0>d.MoveNext() + 0x256
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.Cloud.Services.BaseCloudService.<RegularInvoke>d__10`1.MoveNext() + 0x118

   --- End of inner exception stack trace ---
   at Tacx.Cloud.Services.BaseCloudService.<RegularInvoke>d__10`1.MoveNext() + 0x1d4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.Cloud.Services.UserCloudService.<UserGetJwtAsync>d__25.MoveNext() + 0x111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Polly.NoOp.NoOpEngine.<ImplementationAsync>d__1`1.MoveNext() + 0x10a
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext() + 0x1cb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.Cloud.Services.UserCloudService.<GetJwtAsync>d__11.MoveNext() + 0x11c
   at Tacx.Cloud.Exceptions.ExceptionHandler.HandleRecentRidesExceptions(Exception) + 0x3f
   at Tacx.Cloud.Services.UserCloudService.<GetJwtAsync>d__11.MoveNext() + 0x17a
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Tacx.UWP.Services.Contestants.LiveOpponents.FirebaseTokenGenerator.<GetTokenInternalAsync>d__16.MoveNext() + 0x168

59|2024-09-18T12:20:42.6850645+00:00|INFO|2|VaultService|Could not retrieve token with identifier GarminTokenToken from the vault.
60|2024-09-18T12:20:42.6890611+00:00|INFO|2|VaultService|No tokens with identifier GarminTokenToken found in the vault.
61|2024-09-18T12:20:42.6910600+00:00|INFO|2|VaultService|No tokens with identifier GarminRefreshTokenToken found in the vault.
62|2024-09-18T12:20:42.7910022+00:00|INFO|2|VaultService|Could not retrieve token with identifier GoogleToken from the vault.
63|2024-09-18T12:20:42.7940008+00:00|INFO|2|VaultService|Could not retrieve token with identifier GarminTokenToken from the vault.
65|2024-09-18T12:20:42.9259251+00:00|INFO|2|LoginView|New
66|2024-09-18T12:20:42.9269244+00:00|ERROR|2|LiveOpponentsOnWorkoutCountService|Error while opening connection to https://tacx-cloud.firebaseio.com/v3/workoutData.json --> System.Net.Http.HttpRequestException
67|2024-09-18T12:20:42.9938856+00:00|INFO|2|LoginView|Loaded LoginView
69|2024-09-18T12:20:42.9948854+00:00|INFO|2|LoginViewModel|Loaded LoginViewModel
70|2024-09-18T12:20:42.9948854+00:00|INFO|2|AnalysisLogService|**VIEW_LOAD:{"view":"Login"}
71|2024-09-18T12:20:42.9948854+00:00|INFO|2|AnalysisLogService|**LOGIN_START
73|2024-09-18T12:20:46.3869381+00:00|FATAL|53|Application|Task failure. --> System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Response status code does not indicate success: 401 (Unauthorized).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() + 0xa0
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext() + 0x175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at AimFirebase.FirebaseSubscription.<OpenAsync>d__25.MoveNext() + 0x3fb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at AimFirebase.FirebaseListSubscription`1.<StartAsync>d__8.MoveNext() + 0x1c9

   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() + 0xa0
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext() + 0x175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at AimFirebase.FirebaseSubscription.<OpenAsync>d__25.MoveNext() + 0x3fb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at AimFirebase.FirebaseListSubscription`1.<StartAsync>d__8.MoveNext() + 0x1c9
<---

